os: osx
language: objective-c
osx_image: xcode10.1
xcode_project: BlueShell.xcodeproj
xcode_scheme: BlueShell
xcode_destination: platform=macOS
branches:
  only:
    -master
notifications:
  email:
    recipients:
      - wnnwoo@163.com
    on_success: never
    on_failure: always
